version: '3.4'

services:
  msestiam:
    image: msestiam
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4040:4040
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
